services:
  - type: web
    name: mediabridge-processing-api
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: pnpm install --frozen-lockfile --prod
    startCommand: >-
      API_PORT=$PORT
      API_URL=$RENDER_EXTERNAL_URL
      pnpm --dir api start
    healthCheckPath: /healthz
    autoDeployTrigger: checksPass
    numInstances: 1
    maxShutdownDelaySeconds: 60
    envVars:
      - key: NODE_VERSION
        value: 24.21.0
      - key: API_LISTEN_ADDRESS
        value: 0.0.0.0
      - key: CORS_WILDCARD
        value: "0"
      - key: CORS_URL
        value: https://titonax.github.io
      - key: YOUTUBE_INVIDIOUS_INSTANCES
        value: >-
          https://inv.nadeko.net,
          https://invidious.nerdvpn.de,
          https://yt.chocolatemoo53.com,
          https://invidious.tiekoetter.com
