import test from "node:test";
import assert from "node:assert/strict";

import {
    adaptPipedVideo,
    createPipedProvider,
} from "./piped.js";

const fixture = {
    title: "Example video",
    uploader: "Example channel",
    description: "description",
    duration: 123,
    livestream: false,
    proxyUrl: "https://proxy.example/",
    thumbnailUrl: "/thumb.jpg",
    videoStreams: [
        {
            itag: 22,
            url: "/muxed.mp4",
            mimeType: "video/mp4",
            codec: "avc1.64001F",
            quality: "720p",
            width: 1280,
            height: 720,
            bitrate: 2000000,
            contentLength: 900000,
            videoOnly: false,
        },
        {
            itag: 137,
            url: "/video.mp4",
            mimeType: "video/mp4",
            codec: "avc1.640028",
            quality: "1080p",
            width: 1920,
            height: 1080,
            bitrate: 4000000,
            contentLength: 1000000,
            videoOnly: true,
        },
    ],
    audioStreams: [
        {
            itag: 140,
            url: "/audio.m4a",
            mimeType: "audio/mp4",
            codec: "mp4a.40.2",
            bitrate: 128000,
            contentLength: 100000,
            audioTrackType: "ORIGINAL",
        },
    ],
    subtitles: [
        {
            autoGenerated: false,
            code: "en",
            url: "/captions.vtt",
        },
    ],
};

test("adapts Piped streams to the existing YouTube pipeline", () => {
    const info = adaptPipedVideo(
        {
            ...fixture,
            videoId: "abcdefghijk",
        },
        "https://api.example/"
    );

    assert.equal(info.playability_status.status, "OK");
    assert.equal(info.basic_info.id, "abcdefghijk");
    assert.equal(info.basic_info.title, fixture.title);

    const formats = info.streaming_data.adaptive_formats;
    assert.equal(formats.length, 2);

    const video = formats.find(format => format.has_video);
    const audio = formats.find(format => format.has_audio);

    assert.equal(video.itag, 137);
    assert.equal(video.width, 1920);
    assert.equal(video.height, 1080);
    assert.match(video.mime_type, /avc1\.640028/);
    assert.equal(video.url, "https://proxy.example/video.mp4");

    assert.equal(audio.itag, 140);
    assert.match(audio.mime_type, /mp4a\.40\.2/);
    assert.equal(audio.url, "https://proxy.example/audio.m4a");

    assert.equal(
        info.captions.caption_tracks[0].base_url,
        "https://proxy.example/captions.vtt"
    );
});

test("provider moves to the next instance after a failure", async () => {
    const calls = [];
    const provider = createPipedProvider();

    const result = await provider.resolve({
        videoId: "abcdefghijk",
        instances: [
            "https://one.example/",
            "https://two.example/",
        ],
        log: {},
        fetchImpl: async (url) => {
            calls.push(url.toString());

            if (url.host === "one.example") {
                return {
                    ok: false,
                    status: 503,
                };
            }

            return {
                ok: true,
                status: 200,
                json: async () => fixture,
            };
        },
    });

    assert.equal(result.instance, "https://two.example/");
    assert.equal(result.provider, "piped");
    assert.equal(calls.length, 2);
    assert.match(calls[0], /\/streams\/abcdefghijk$/);
});

test("failed Piped instances enter cooldown", async () => {
    let clock = 1000;
    const calls = [];
    const provider = createPipedProvider({
        now: () => clock,
        cooldownMs: 5000,
    });

    const resolve = () => provider.resolve({
        videoId: "abcdefghijk",
        instances: [
            "https://one.example/",
            "https://two.example/",
        ],
        log: {},
        fetchImpl: async (url) => {
            calls.push(url.host);

            if (url.host === "one.example") {
                return {
                    ok: false,
                    status: 500,
                };
            }

            return {
                ok: true,
                status: 200,
                json: async () => fixture,
            };
        },
    });

    await resolve();
    await resolve();

    assert.deepEqual(calls, [
        "one.example",
        "two.example",
        "two.example",
    ]);

    clock += 6000;
    await resolve();

    assert.equal(calls.at(-2), "one.example");
    assert.equal(calls.at(-1), "two.example");
});
