const DEFAULT_COOLDOWN_MS = 5 * 60 * 1000;
const DEFAULT_TIMEOUT_MS = 10 * 1000;

const absoluteUrl = (value, base) => {
    if (!value) return value;

    try {
        return new URL(value, base).toString();
    } catch {
        return value;
    }
};

const mimeWithCodec = (stream, fallbackType) => {
    const mime = stream?.mimeType || fallbackType;
    const codec = stream?.codec;

    if (!codec || mime.includes("codecs=")) {
        return mime;
    }

    return `${mime}; codecs="${codec}"`;
};

const normalizeVideo = (stream, base) => ({
    itag: stream.itag,
    mime_type: mimeWithCodec(stream, "video/mp4"),
    content_length: stream.contentLength,
    bitrate: Number(stream.bitrate) || 0,
    width: Number(stream.width) || undefined,
    height: Number(stream.height) || undefined,
    has_video: true,
    has_audio: false,
    url: absoluteUrl(stream.url, base),
    is_original: true,
});

const normalizeAudio = (stream, base) => ({
    itag: stream.itag,
    mime_type: mimeWithCodec(stream, "audio/mp4"),
    content_length: stream.contentLength,
    bitrate: Number(stream.bitrate) || 0,
    has_video: false,
    has_audio: true,
    url: absoluteUrl(stream.url, base),
    language: stream.audioTrackLocale,
    audio_track: stream.audioTrackId,
    is_original: !stream.audioTrackType
        || stream.audioTrackType === "ORIGINAL",
});

export const adaptPipedVideo = (video, instance) => {
    const mediaBase = video.proxyUrl || instance;

    const rawVideoStreams = Array.isArray(video.videoStreams)
        ? video.videoStreams
        : [];
    const videoOnly = rawVideoStreams.filter(stream => stream.videoOnly);
    const selectedVideoStreams = videoOnly.length
        ? videoOnly
        : rawVideoStreams;

    const videoFormats = selectedVideoStreams
        .map(stream => normalizeVideo(stream, mediaBase))
        .filter(format => format.url && format.content_length);

    const audioFormats = (video.audioStreams || [])
        .map(stream => normalizeAudio(stream, mediaBase))
        .filter(format => format.url && format.content_length);

    return {
        playability_status: {
            status: "OK",
        },
        basic_info: {
            id: video.videoId,
            title: video.title || "",
            author: video.uploader || "YouTube",
            duration: Number(video.duration) || 0,
            is_live: Boolean(video.livestream),
            short_description: video.description || "",
            thumbnail: video.thumbnailUrl
                ? [{ url: absoluteUrl(video.thumbnailUrl, mediaBase) }]
                : [],
        },
        streaming_data: {
            adaptive_formats: [
                ...videoFormats,
                ...audioFormats,
            ],
            hls_manifest_url: absoluteUrl(video.hls, mediaBase),
        },
        captions: {
            caption_tracks: (video.subtitles || []).map(subtitle => ({
                kind: subtitle.autoGenerated ? "asr" : undefined,
                language_code: subtitle.code,
                base_url: absoluteUrl(subtitle.url, mediaBase),
            })),
        },
    };
};

const normalizeInstance = (value) => {
    const url = new URL(value);

    if (!["http:", "https:"].includes(url.protocol)) {
        throw new Error("unsupported protocol");
    }

    url.pathname = "/";
    url.search = "";
    url.hash = "";

    return url.toString();
};

export const createPipedProvider = ({
    now = () => Date.now(),
    cooldownMs = DEFAULT_COOLDOWN_MS,
    timeoutMs = DEFAULT_TIMEOUT_MS,
} = {}) => {
    const blockedUntil = new Map();

    return {
        name: "piped",

        async resolve({
            videoId,
            instances,
            dispatcher,
            fetchImpl,
            log = console,
        }) {
            if (!fetchImpl || !videoId || !instances?.length) {
                return;
            }

            for (const rawInstance of instances) {
                let instance;

                try {
                    instance = normalizeInstance(rawInstance);
                } catch {
                    log.warn?.(
                        `[youtube] provider=piped instance=${rawInstance} result=invalid_instance`
                    );
                    continue;
                }

                const host = new URL(instance).host;
                const unavailableUntil = blockedUntil.get(instance) || 0;

                if (unavailableUntil > now()) {
                    log.info?.(
                        `[youtube] provider=piped instance=${host} result=cooldown`
                    );
                    continue;
                }

                try {
                    const endpoint = new URL(
                        `/streams/${encodeURIComponent(videoId)}`,
                        instance
                    );

                    const response = await fetchImpl(endpoint, {
                        dispatcher,
                        headers: {
                            accept: "application/json",
                        },
                        signal: AbortSignal.timeout(timeoutMs),
                    });

                    if (!response.ok) {
                        throw new Error(`HTTP ${response.status}`);
                    }

                    const payload = await response.json();

                    if (
                        !Array.isArray(payload?.videoStreams)
                        || !Array.isArray(payload?.audioStreams)
                    ) {
                        throw new Error("invalid streams payload");
                    }

                    const info = adaptPipedVideo(
                        {
                            ...payload,
                            videoId,
                        },
                        instance
                    );

                    const hasVideo = info.streaming_data.adaptive_formats
                        .some(format => format.has_video);
                    const hasAudio = info.streaming_data.adaptive_formats
                        .some(format => format.has_audio);

                    if (!hasVideo || !hasAudio) {
                        throw new Error("missing adaptive media");
                    }

                    blockedUntil.delete(instance);

                    log.info?.(
                        `[youtube] provider=piped instance=${host} result=ok formats=${info.streaming_data.adaptive_formats.length}`
                    );

                    return {
                        provider: "piped",
                        instance,
                        info,
                    };
                } catch (error) {
                    blockedUntil.set(instance, now() + cooldownMs);

                    log.warn?.(
                        `[youtube] provider=piped instance=${host} result=fail reason=${error?.message || error}`
                    );
                }
            }
        },
    };
};

export const pipedProvider = createPipedProvider();
